=== Xukialb/AE-2-XML-DTD-y-XSD/Anabella/Anabella_biblioteca02.xsd
<?xml version="1.0" encoding="utf-8"?>

<schema xmlns="http://www.w3.org/2001/XMLSchema">
    <element name="biblioteca">
        <complexType>
            <sequence>
                <element name="libros">
                    <complexType>
                        <sequence>
                            <element name="libro">
                                <complexType>
                                    <sequence>
                                        <element name="titulo" type="string" />
                                        <element name="sinopsis" type="string" />
                                        <element name="indice">
                                            <complexType>
                                                <sequence>
                                                    <element maxOccurs="unbounded" name="item">
                                                        <complexType>
                                                            <simpleContent>
                                                                <extension base="string">
                                                                    <attribute name="pagina" type="integer" use="required" />
                                                                </extension>
                                                            </simpleContent>
                                                        </complexType>
                                                    </element>
                                                </sequence>
                                            </complexType>
                                        </element>
                                        <element name="capitulos">
                                            <complexType>
                                                <sequence>
                                                    <element maxOccurs="unbounded" name="capitulo">
                                                        <complexType>
                                                            <sequence>
                                                                <element name="contenido">
                                                        <complexType>
                                                            <attribute name="enlace" type="string" use="required" />
                                                        </complexType>
                                                    </element>
                                                        </sequence>
                                                        <attribute name="id_capitulo" type="string" use="required" />
                                                        <attribute name="titulo_cap" type="string" use="required" />
                                                        <attribute name="paginas" type="integer" use="required" />
                                                    </complexType>
                                                </element>
                                                </sequence>
                                            </complexType>
                                        </element>
                                    </sequence>
                                    <attribute name="id" type="string" use="required" />
                                    <attribute name="tipo_clase" type="string" use="required" />
                                </complexType>
                            </element>
                        </sequence>
                    </complexType>
                </element>
                <element name="revistas">
                    <complexType>
                        <sequence>
                            <element name="revista">
                                <complexType>
                                    <sequence>
                                        <element name="titulo_rev" type="string" />
                                        <element name="numero" type="integer" />
                                        <element name="indice_rev">
                                            <complexType>
                                                <sequence>
                                                    <element maxOccurs="unbounded" name="item">
                                                        <complexType>
                                                            <simpleContent>
                                                                <extension base="string">
                                                                    <attribute name="pagina" type="integer" use="required" />
                                                                </extension>
                                                            </simpleContent>
                                                        </complexType>
                                                    </element>
                                                </sequence>
                                            </complexType>
                                        </element>
                                        <element name="secciones">
                                            <complexType>
                                                <sequence>
                                                    <element maxOccurs="unbounded" name="seccion">
                                                        <complexType>
                                                            <sequence>
                                                                <element name="seccion_r">
                                                                    <complexType>
                                                                        <attribute name="titulo" type="string" use="required" />
                                                                        <attribute name="paginas" type="integer" use="required" />
                                                                    </complexType>
                                                                </element>
                                                                <element name="contenido_rev">
                                                                    <complexType>
                                                                        <attribute name="enlace" type="string" use="required" />
                                                                    </complexType>
                                                                </element>
                                                            </sequence>
                                                        </complexType>
                                                    </element>
                                                </sequence>
                                            </complexType>
                                        </element>
                                    </sequence>
                                    <attribute name="id" type="string" use="required" />
                                    <attribute name="tipo_clase" type="string" use="required" />
                                </complexType>
                            </element>
                        </sequence>
                    </complexType>
                </element>
                <element name="periodicos">
                    <complexType>
                        <sequence>
                            <element name="periodico">
                                <complexType>
                                    <sequence>
                                        <element name="secciones">
                                            <complexType>
                                                <sequence>
                                                    <element maxOccurs="unbounded" name="seccion_per">
                                                        <complexType>
                                                            <sequence>
                                                                <element name="articulo">
                                                                    <complexType>
                                                                        <simpleContent>
                                                                            <extension base="string">
                                                                                <attribute name="autor" type="string" use="required" />
                                                                            </extension>
                                                                        </simpleContent>
                                                                    </complexType>
                                                                </element>
                                                                <element name="contenido_p">
                                                                    <complexType>
                                                                        <attribute name="enlace" type="string" use="required" />
                                                                    </complexType>
                                                                </element>
                                                            </sequence>
                                                            <attribute name="tipo_seccion" type="string" use="required" />
                                                        </complexType>
                                                    </element>
                                                </sequence>
                                            </complexType>
                                        </element>
                                    </sequence>
                                    <attribute name="id" type="string" use="required" />
                                    <attribute name="tipo_clase" type="string" use="required" />
                                    <attribute name="fecha_publicacion" type="date" use="required" />
                                </complexType>
                            </element>
                        </sequence>
                    </complexType>
                </element>
            </sequence>
        </complexType>
    </element>
</schema>

=== Xukialb/AE-2-XML-DTD-y-XSD/Anabella/Anabella_biblioteca02.xml
<?xml version="1.0" encoding="UTF-8"?>
<biblioteca xsi:noNamespaceSchemaLocation="Anabella_biblioteca02.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
        <biblioteca>
    <libros>
        <libro id="L123" tipo_clase="novela">
            <titulo>Nadie queda atrás</titulo>
            <sinopsis></sinopsis>
             <indice>
                <item pagina="1">Para comenzar</item>
                <item pagina="15">Silencio</item>
                <item pagina="26">Tiempo y esfuerzo</item>
                <item pagina="38">Seguir</item>
                <item pagina="54">Supremacía</item>
            </indice>         
            <capitulo id_capitulo="L123C1" titulo_cap= "Para comenzar" paginas="14"> </capitulo>
                <contenido enlace="capitulo1.txt"></contenido>           
            <capitulo id_capitulo="L123C2" titulo_cap="Silencio" paginas="11"> </capitulo> 
                <contenido enlace="capitulo2.txt" ></contenido>           
             <capitulo id_capitulo="L123C3" titulo_cap="Tiempo y esfuerzo" paginas="12"></capitulo>
                <contenido enlace="capitulo3.txt"></contenido>              
            <capitulo id_capitulo="L123C4" titulo_cap= "Seguir" paginas="16"> </capitulo>
                <contenido enlace="capitulo4.txt"></contenido>                
            <capitulo id_capitulo="L123C5" titulo_cap= "Supremacía" paginas="12"></capitulo>  
                <contenido enlace="capitulo5.txt"></contenido>            
        </libro>
    </libros>
    <revistas>
        <revista id_rev="R001" tipo_clase="coches">
            <titulo_rev>Lanzamientos 2023</titulo_rev>
            <numero>1</numero>
            <indice_rev> 
                <item pagina="1">Lo nuevo para este año</item>
                <item pagina="9">Estilo y confort</item>
                <item pagina="13">Los más vendidos</item>
            </indice_rev>
            <seccion_r titulo="Lo nuevo para este año" paginas="8"> </seccion_r>
                <contenido_rev enlace="url"></contenido_rev>      
            <seccion_r titulo="Estilo y confort" paginas="5"> </seccion_r>
                <contenido_sec enlace="url"></contenido_sec>  
            <seccion_r titulo="Los más vendidos" paginas="10"></seccion_r>
                <contenido_sec enlace="url"></contenido_sec>   
            <paginas>23</paginas>
        </revista>
    </revistas>
    <periodicos>
        <periodico id_per="P101" tipo_clase="nacional" fecha_publicacion="2023-04-11">
            <secciones>
                <seccion_per tipo_seccion="economica"> 
                <articulo autor="Marta Rivas">Nuevos fondos de inversión</articulo>
                <contenido_p enlace="url"></contenido_p>
                </seccion_per>
                <seccion_per tipo_seccion="opinion">
                <articulo autor="Sol Harf">"Entre tazas de cafe"</articulo>
                <contenido_p enlace="url"></contenido_p>
                </seccion_per>
                <seccion_per tipo_seccion="deportes">
                    <articulo autor="Marta Re">"El superclasico..."</articulo>
                    <contenido_p enlace="url"></contenido_p>
                </seccion_per> 
                <seccion_per tipo_seccion="internacional">
                    <articulo autor="Juan Cuevas">"Tensión en medio oriente"</articulo>
                    <contenido_p enlace="url"></contenido_p>
                </seccion_per>           
                <seccion_per tipo_seccion="nacional">
                    <articulo autor="Emilio Suris">"Bajas en los indices de desempleo"</articulo>
                    <contenido_p enlace="url"></contenido_p>
                </seccion_per>                            
            </secciones>
        </periodico>
    </periodicos>
</biblioteca>
