=== Xukialb/AE-2-XML-DTD-y-XSD/Cristina/biblioteca.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:simpleType name="tipo_id"> 
 <xs:restriction base="xs:string">
  <xs:pattern value="[L]{1}\d{4}"></xs:pattern>
   <xs:pattern value="[P]{1}\d{4}"></xs:pattern>
    <xs:pattern value="[R]{1}\d{4}"></xs:pattern>
 </xs:restriction>
</xs:simpleType>


<xs:simpleType name="tipo_clase"> 
 <xs:restriction base="xs:string">
  <xs:enumeration value="Novela"></xs:enumeration>
   <xs:enumeration value="Infantil"></xs:enumeration>
   <xs:enumeration value="Didactico"></xs:enumeration>
    <xs:enumeration value="Nacional"></xs:enumeration>
     <xs:enumeration value="Internacional"></xs:enumeration>
      <xs:enumeration value="Informatica"></xs:enumeration>
       <xs:enumeration value="Investigacion"></xs:enumeration>
        <xs:enumeration value="Corazon"></xs:enumeration>
 </xs:restriction>
</xs:simpleType>

  <xs:element name="biblioteca">
   <xs:complexType>
    <xs:sequence>
     <xs:element name="libros">   
      <xs:complexType>
       <xs:sequence>
        <xs:element name="libro"  minOccurs="1"  maxOccurs="unbounded">
         <xs:complexType>
          <xs:sequence>
           <xs:element name="titulo_libro" type="xs:string"></xs:element>
            <xs:element name="capitulos" >
             <xs:complexType>
              <xs:sequence>
               <xs:element name="capitulo" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                 <xs:sequence>
                  <xs:element name="cap_titulo" type="xs:string"></xs:element>
                  <xs:element name="cap_contenido" >
                   <xs:complexType>
                    <xs:simpleContent>
                     <xs:extension base="xs:string">
                      <xs:attribute name="informacion" use="required"></xs:attribute>
                     </xs:extension>
                    </xs:simpleContent>
                   </xs:complexType> 
                  </xs:element>
                 </xs:sequence>
                  <xs:attribute name="tipo" type="xs:string" use="required"></xs:attribute>
                  <xs:attribute name="num_paginas" type="xs:integer"></xs:attribute>
                </xs:complexType>
               </xs:element>
              </xs:sequence>
             </xs:complexType>
            </xs:element>
            <xs:element name="indice_libro" type="xs:string"></xs:element>
            <xs:element name="sinopsis" type="xs:string"></xs:element>
          </xs:sequence>
          <xs:attribute name="id"  type="tipo_id" use="required"></xs:attribute>
          <xs:attribute name="tipo_clase" type="tipo_clase" use="required"></xs:attribute>
          <xs:attribute name="num_paginas" type="xs:integer"></xs:attribute>
         </xs:complexType>
        </xs:element>
       </xs:sequence> 
      </xs:complexType>
     </xs:element>
     <xs:element name="periodicos">       
      <xs:complexType>
       <xs:sequence>
        <xs:element name="periodico" minOccurs="1"  maxOccurs="unbounded">
         <xs:complexType>
          <xs:sequence>
           <xs:element name="secciones_periodico" minOccurs="1" maxOccurs="unbounded">   
            <xs:complexType>
            <xs:sequence>
              <xs:element name="seccion_per" minOccurs="1" maxOccurs="unbounded">  
               <xs:complexType>
                <xs:sequence>
                 <xs:element name="articulo"> 
                  <xs:complexType>
                   <xs:simpleContent>
                    <xs:extension base="xs:string">
                     <xs:attribute name="autor"></xs:attribute>
                    </xs:extension>
                   </xs:simpleContent>
                  </xs:complexType>
                 </xs:element>
                </xs:sequence>
                <xs:attribute name="tipo" type="xs:string" use="required"></xs:attribute>
               </xs:complexType>
              </xs:element>
             </xs:sequence>
            </xs:complexType>
           </xs:element>
           <xs:element name="indice_periodico" type="xs:string"></xs:element>
           <xs:element name="contenido_periodico">
            <xs:complexType> 
             <xs:simpleContent>
              <xs:extension base="xs:string"> 
               <xs:attribute name="inform" type="xs:string" use="required"></xs:attribute>
              </xs:extension>
             </xs:simpleContent>
            </xs:complexType>
           </xs:element>
          </xs:sequence>
          <xs:attribute name="id" type="tipo_id" use="required"></xs:attribute>
          <xs:attribute name="tipo_clase" type="tipo_clase"></xs:attribute>
          <xs:attribute name="fecha_publicacion" type="xs:date" use="required"> </xs:attribute>
         </xs:complexType>      
        </xs:element> 
       </xs:sequence>
      </xs:complexType>
     </xs:element>
   <xs:element name="revistas">  
    <xs:complexType>
     <xs:sequence>
      <xs:element name="revista" minOccurs="1" maxOccurs="unbounded"> 
       <xs:complexType>
        <xs:sequence>
         <xs:element name="titulo_revista" type="xs:string"> </xs:element>
         <xs:element name="numero" type="xs:integer"></xs:element>
         <xs:element name="indice_revista" type="xs:string"></xs:element>
         <xs:element name="contenido_revista" type="xs:string"></xs:element>
         <xs:element name="secciones_revista" minOccurs="1" maxOccurs="unbounded">
          <xs:complexType>
           <xs:sequence>
            <xs:element name="seccion_rev" minOccurs="1" maxOccurs="unbounded">  
             <xs:complexType>
              <xs:sequence>
               <xs:element name="contenido">
                <xs:complexType>
                 <xs:simpleContent>
                  <xs:extension base="xs:string">
                   <xs:attribute name="informacion" type="xs:string" use="required"></xs:attribute>
                  </xs:extension>
                 </xs:simpleContent>
                </xs:complexType>
               </xs:element>
              </xs:sequence>
              <xs:attribute name="tipo" type="xs:string" use="required"></xs:attribute>
              <xs:attribute name="num_paginas" type="xs:integer"></xs:attribute>
             </xs:complexType> 
            </xs:element>
           </xs:sequence>
          </xs:complexType>
         </xs:element>
        </xs:sequence>
        <xs:attribute name="id" type="tipo_id" use="required"></xs:attribute>
        <xs:attribute name="tipo_clase" type="tipo_clase" use="required"></xs:attribute>
        <xs:attribute name="num_paginas" type="xs:integer" ></xs:attribute>
       </xs:complexType>  
      </xs:element>
     </xs:sequence>
    </xs:complexType>
   </xs:element>
  </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>

=== Xukialb/AE-2-XML-DTD-y-XSD/Cristina/biblioteca.xml
<?xml version="1.0" encoding="UTF-8"?>

<biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:noNamespaceSchemaLocation="biblioteca.xsd">
  <libros>
     <libro id="L1234" tipo_clase="Novela" num_paginas="365">
        <titulo_libro> El jardin embrujado </titulo_libro>
        <capitulos>  
           <capitulo tipo="Uno" num_paginas="5">
             <cap_titulo>Capitulo 1</cap_titulo>
             <cap_contenido informacion="url.capitulo1">info.cap</cap_contenido> 
           </capitulo>
           <capitulo tipo="Dos" num_paginas="12">
              <cap_titulo>Capitulo 2</cap_titulo>
              <cap_contenido informacion="url.capitulo2">info.cap</cap_contenido> 
           </capitulo>
           <capitulo tipo="Tres" num_paginas="23">
             <cap_titulo>Capitulo 3</cap_titulo>
             <cap_contenido informacion="url.capitulo3">info.cap</cap_contenido> 
           </capitulo>
        </capitulos>
        <indice_libro> Indice</indice_libro>
        <sinopsis> Sinopsis </sinopsis>
     </libro>     

     <libro id="L3456" tipo_clase="Infantil" num_paginas="32">
        <titulo_libro> Zoe es una princesa </titulo_libro>
        <capitulos>  
           <capitulo tipo="Parte1" num_paginas="2">
             <cap_titulo>Capitulo 1</cap_titulo>
             <cap_contenido informacion="url.capitulo1">info.cap</cap_contenido> 
           </capitulo>
           <capitulo tipo="Parte2" num_paginas="4">
             <cap_titulo>Capitulo 2</cap_titulo>
             <cap_contenido informacion="url.capitulo2">info.cap</cap_contenido> 
           </capitulo>
           <capitulo tipo="Parte3" num_paginas="4">
             <cap_titulo>Capitulo 3</cap_titulo>
             <cap_contenido informacion="url.capitulo3">info.cap</cap_contenido> 
           </capitulo>
        </capitulos>
        <indice_libro> Indice</indice_libro>
        <sinopsis> Sinopsis </sinopsis>
     </libro>   

     <libro id="L7891" tipo_clase="Didactico" num_paginas="165">
        <titulo_libro> Botanica </titulo_libro>
        <capitulos>  
           <capitulo tipo="Primero" num_paginas="6">
             <cap_titulo>Capitulo 1</cap_titulo>
             <cap_contenido informacion="url.capitulo1">info.cap</cap_contenido> 
           </capitulo>
           <capitulo tipo="Segundo" num_paginas="10">
             <cap_titulo>Capitulo 2</cap_titulo>
             <cap_contenido informacion="url.capitulo2">info.cap</cap_contenido> 
           </capitulo>
           <capitulo tipo="Tercero" num_paginas="14">
             <cap_titulo>Capitulo 3</cap_titulo>
             <cap_contenido informacion="url.capitulo3">info.cap</cap_contenido> 
           </capitulo>
        </capitulos>
        <indice_libro> Indice</indice_libro>
        <sinopsis> Sinopsis </sinopsis>
      </libro>  
    </libros> 

     <periodicos>
       <periodico id="P2345" tipo_clase="Nacional" fecha_publicacion="2014-05-27">
         <secciones_periodico> 
            <seccion_per tipo="economia">
               <articulo autor="Ronaldo Espinosa">La crisis economica en los estados europeos</articulo>
            </seccion_per> 
            <seccion_per tipo="opinion" >
               <articulo autor="Ivan Romero">Los peligros ocultos del avance de la IA</articulo>
            </seccion_per>
            <seccion_per tipo="deportes">
               <articulo autor="Sara Hernandez">Los ganadores de la Champions</articulo>
            </seccion_per>
            <seccion_per tipo="nacional"> 
               <articulo autor="Ivan Romero">Los cambios en la politica nacional</articulo>
            </seccion_per>
            <seccion_per tipo="internacional">
                <articulo autor="Fernando Garzon">Impacto del cambio climatico en la economia global</articulo>
            </seccion_per>
         </secciones_periodico>
         <indice_periodico> Indice </indice_periodico>
         <contenido_periodico inform="url.periodico">Contenido</contenido_periodico>
       </periodico>  


       <periodico id="P3984" tipo_clase="Internacional" fecha_publicacion="2019-12-09">
         <secciones_periodico> 
           <seccion_per tipo="economia">
               <articulo autor="Frank Donalson">La gran crisis de Estados Unidos</articulo>
           </seccion_per> 
           <seccion_per tipo="opinion" >
               <articulo autor="Ray Stuart">Los peligros del cambio de ideologia de las nuevas generaciones </articulo>
           </seccion_per>
           <seccion_per tipo="deportes">
               <articulo autor="Sandra Clinton">La exclusion de los atletas rusos en las olimpiadas</articulo>
           </seccion_per>
           <seccion_per tipo="internacional">
               <articulo autor="Boris Jonson">Impacto del cambio climatico en la economia global</articulo>
           </seccion_per>
         </secciones_periodico>
         <indice_periodico> Indice </indice_periodico>
         <contenido_periodico inform="url.periodico">Contenido</contenido_periodico>
       </periodico>  
    </periodicos>

   <revistas>
     <revista id="R9634" tipo_clase="Informatica" num_paginas="12">
         <titulo_revista>Mundo Digital</titulo_revista>
         <numero>234</numero>
         <indice_revista>Indice </indice_revista>
         <contenido_revista>Contenido</contenido_revista>
         <secciones_revista>
            <seccion_rev tipo="Lo ultimo en tecnologia" num_paginas="3">
              <contenido informacion="url.seccion1">Contenido </contenido>
            </seccion_rev>
            <seccion_rev tipo="Nuevos avances tecnologicos" num_paginas="4">
               <contenido informacion="url.seccion2">Contenido </contenido>
            </seccion_rev>
             <seccion_rev tipo="Emprendimiento" num_paginas="2">
                <contenido informacion="url.seccion3">Contenido </contenido>
            </seccion_rev>  
         </secciones_revista>
     </revista>
    

     <revista id="R3456" tipo_clase="Investigacion" num_paginas="16">
         <titulo_revista>Equipo de investigacion</titulo_revista>
         <numero>42</numero>
         <indice_revista>Indice </indice_revista>
         <contenido_revista>Contenido </contenido_revista>
         <secciones_revista>
            <seccion_rev tipo="Novedades" num_paginas="3">
              <contenido informacion="url.seccion1">Contenido </contenido>
            </seccion_rev>
            <seccion_rev tipo="Desarollo" num_paginas="2">
               <contenido informacion="url.seccion2">Contenido </contenido>
            </seccion_rev>
             <seccion_rev tipo="Curisidades" num_paginas="4">
                <contenido informacion="url.seccion3">Contenido </contenido>
            </seccion_rev>
         </secciones_revista>
      </revista>

      <revista id="R3536" tipo_clase="Corazon" num_paginas="16">
         <titulo_revista>Lola</titulo_revista>
         <numero>1235</numero>
         <indice_revista>Indice </indice_revista>
         <contenido_revista>Contenido </contenido_revista>
         <secciones_revista>
            <seccion_rev tipo="La boda del mes " num_paginas="3">
              <contenido informacion="url.seccion1">Contenido </contenido>
            </seccion_rev>
            <seccion_rev tipo="Lo ultimo de la temporada " num_paginas="2">
               <contenido informacion="url.seccion2">Contenido </contenido>
            </seccion_rev>
             <seccion_rev tipo="Moda" num_paginas="4">
                 <contenido informacion="url.seccion3">Contenido </contenido>
            </seccion_rev>
         </secciones_revista>
       </revista>
      </revistas>
</biblioteca>
