<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Biblioteca [
    <!ELEMENT Biblioteca (Libro*,Periódico*,Revista*)>

    <!ELEMENT Libro (Título_lib,Autor?,Sinopsis,Indice_lib,Año_publicación?,Editorial?)>
    <!ATTLIST Libro Id ID #REQUIRED>
    <!ATTLIST Libro tipo_clase (novela | infantil | didáctico) #REQUIRED>
    <!ATTLIST Libro num_paginas CDATA #REQUIRED>
    <!ELEMENT Título_lib (#PCDATA)>
    <!ELEMENT Autor (#PCDATA)>
    <!ELEMENT Sinopsis (#PCDATA)>
    <!ELEMENT Indice_lib (Capítulo_lib*)>

    <!ELEMENT Capítulo_lib (Contenido_cap*)>
    <!ATTLIST Capítulo_lib páginas CDATA #REQUIRED> 

    <!ELEMENT Contenido_cap (#PCDATA)>
    <!ATTLIST Contenido_cap información CDATA #REQUIRED>

    <!ELEMENT Año_publicación (#PCDATA)>
    <!ELEMENT Editorial (#PCDATA)>
    <!ENTITY Cap "Capítulo">


    <!ELEMENT Periódico (Secciones_per,Indice)>
    <!ATTLIST Periódico Id ID #REQUIRED>
    <!ATTLIST Periódico tipo_clase (nacional | internacional) #REQUIRED>
    <!ATTLIST Periódico fecha_publicación CDATA #IMPLIED>
    <!ELEMENT Secciones_per (Sección_per+)>

    <!ELEMENT Sección_per (Artículo+)>
    <!ATTLIST Sección_per tipo_sección (Económica | Opinión | Deportes | Nacional | Internacional) #REQUIRED>

    <!ELEMENT Artículo (Contenido_art+)>
    <!ATTLIST Artículo Autor CDATA #REQUIRED>

    <!ELEMENT Contenido_art (#PCDATA)>
    <!ATTLIST Contenido_art Información CDATA #REQUIRED>
    
    <!ELEMENT Indice (#PCDATA)> 


    <!ELEMENT Revista (Título,Número,Indice_de_contenido,Secciones)>
    <!ATTLIST Revista Id ID #REQUIRED>
    <!ATTLIST Revista tipo_clase (informática | corazón | coches | investigación | otras) #REQUIRED>
    <!ATTLIST Revista num_paginas CDATA #REQUIRED>
    <!ELEMENT Título (#PCDATA)>
    <!ELEMENT Número (#PCDATA)>
    <!ELEMENT Indice_de_contenido (#PCDATA)>
    <!ELEMENT Secciones (Sección*)>
    <!ELEMENT Sección (Contenido*)>
    <!ATTLIST Sección num_paginas CDATA #REQUIRED>

    <!ELEMENT Contenido (#PCDATA)> 
    <!ATTLIST Contenido información CDATA #REQUIRED>
]>
<Biblioteca>
    <Libro Id="L7514" tipo_clase="novela" num_paginas="522">
        <Título_lib>La sombra del viento</Título_lib>
        <Autor>Carlos Ruiz Zafon</Autor>
        <Sinopsis>Barcelona, 1945: Un muchacho, Daniel Sempere, es llevado por su padre a un misterioso lugar en el corazón del casco antiguo: El Cementerio de los Libros Olvidados. Allí, Daniel encuentra un libro llamado La Sombra del Viento, por Julián Carax, que cambiará su vida para siempre. A medida que Daniel investiga la vida y obra de Carax, se ve arrastrado a un peligroso laberinto de secretos y intrigas que lo llevan al corazón de la Barcelona de la posguerra.</Sinopsis>            
        <Indice_lib>
            <Capítulo_lib páginas="10">
                <Contenido_cap información="gag">Prólogo: La Sombra del Viento</Contenido_cap>
            </Capítulo_lib>                       
            <Capítulo_lib páginas="25">
                <Contenido_cap información="fda">&Cap; 1: La Ciudad de los Prodigios</Contenido_cap>
            </Capítulo_lib>                    
            <Capítulo_lib páginas="32">
                <Contenido_cap información="rwqt">&Cap; 2: La Penumbra de los Sentidos</Contenido_cap>
            </Capítulo_lib>                    
            <Capítulo_lib páginas="18">
                <Contenido_cap información="nrt">&Cap; 3: El Cementerio de los Libros Olvidados</Contenido_cap> 
            </Capítulo_lib>                   
            <Capítulo_lib páginas="22">
                <Contenido_cap información="ewq">&Cap; 4: La Ciudad de las Damas</Contenido_cap>
            </Capítulo_lib>                    
            <Capítulo_lib páginas="14">
                <Contenido_cap información="kiy">&Cap; 5: La Dama del Anís</Contenido_cap>
            </Capítulo_lib>                    
            <Capítulo_lib páginas="19">
                <Contenido_cap información="gfs">&Cap; 6: El Palacio de la Medianoche</Contenido_cap>
            </Capítulo_lib>                    
            <Capítulo_lib páginas="28">
                <Contenido_cap información="fwe">&Cap; 7: La Mujer de Vapor</Contenido_cap>
            </Capítulo_lib>                    
            <Capítulo_lib páginas="27">
                <Contenido_cap información="iuyl">&Cap; 8: El Prisionero del Cielo</Contenido_cap>                
            </Capítulo_lib>
            <Capítulo_lib páginas="16">
                <Contenido_cap información="sDSF">&Cap; 9: El Dominio de las Sombras</Contenido_cap>                
            </Capítulo_lib>
            <Capítulo_lib páginas="20">
                <Contenido_cap información="eqd">&Cap; 10: El Cementerio de los Libros Olvidados II</Contenido_cap> 
            </Capítulo_lib>
        </Indice_lib>
        <Año_publicación>2001</Año_publicación>
        <Editorial>Planeta</Editorial>      
    </Libro> 

    <Periódico Id="P0519" tipo_clase="nacional" fecha_publicación="2023/02/23">
        <Secciones_per>
            <Sección_per tipo_sección="Económica">
                <Artículo Autor="Matias Prats">
                    <Contenido_art Información="fdafad">Se baja el IVA de los productos básicos</Contenido_art>
                </Artículo>
            </Sección_per>
            <Sección_per tipo_sección="Nacional">
                <Artículo Autor="Pedro Piqueras">
                    <Contenido_art Información="djfak">Comienza la precampaña electoral</Contenido_art>
                </Artículo>
            </Sección_per>
            <Sección_per tipo_sección="Internacional">
                <Artículo Autor="Matias Prats">
                    <Contenido_art Información="dfaf">Se firma la paz en Ucrania</Contenido_art>
                </Artículo>
            </Sección_per>
            <Sección_per tipo_sección="Nacional">
                <Artículo Autor="José Ribagorda">
                    <Contenido_art Información="gehr">Huelga de médicos en Madrid</Contenido_art>
                </Artículo>
            </Sección_per>
            <Sección_per tipo_sección="Nacional">
                <Artículo Autor="Isabel Jiménez">
                    <Contenido_art Información="grwe">Comienza la fiesta del cine</Contenido_art>
                </Artículo>
            </Sección_per>   
            <Sección_per tipo_sección="Deportes">
                <Artículo Autor="Matias Prats Jr.">
                    <Contenido_art Información="iuyl">Real Madrid se prepara para las semifinales de la Liga de Campeones</Contenido_art>
                </Artículo>
            </Sección_per>
            <Sección_per tipo_sección="Nacional">
                <Artículo Autor="Roberto Brasero">
                    <Contenido_art Información="htre">Nueva ola de calor llega a la península</Contenido_art>
                </Artículo>
            </Sección_per>     
        </Secciones_per>    
        <Indice >
            -Actualidad
            -Nacional
            -Internacional
            -Local
            -Cultura
            -Deportes
            -El tiempo
            -Anuncios
        </Indice>        
    </Periódico>

    <Revista Id="R0641" tipo_clase="coches" num_paginas="52">
        <Título>CocheActual</Título>
        <Número>52</Número>
        <Indice_de_contenido>
            -Sumario
            -Actualidad
            -Analisis a fondo
            -Anuncios
        </Indice_de_contenido>
        <Secciones>
            <Sección num_paginas="2">
                <Contenido información="https://www.cocheactual.com/los-precios-de-los-automoviles-siguen-mostrando-una-tendencia-al-alza/">Actualidad</Contenido>
            </Sección>
            <Sección num_paginas="2">
                <Contenido información="https://www.cocheactual.com/trabajos-mas-y-menos-afectados-por-la-inteligencia-artificial/">Actualidad</Contenido>
            </Sección>
            <Sección num_paginas="2">
                <Contenido información="https://www.cocheactual.com/reducir-las-emisiones-del-vehiculo-reduciendo-su-masa/">Actualidad</Contenido>
            </Sección>
            <Sección num_paginas="1">
                <Contenido información="https://www.cocheactual.com/reparacion-de-abolladuras-sin-pintar-o-tecnicas-pdr/">Curiosidades</Contenido>
            </Sección>
            <Sección num_paginas="3">
                <Contenido información="https://www.cocheactual.com/cuanto-cobra-un-mecanico-en-espana-que-perfiles-son-los-mas-buscados-en-automocion/">Curiosidades</Contenido>
            </Sección>
            <Sección num_paginas="2">
                <Contenido información="https://www.cocheactual.com/como-la-electromecanica-del-automovil-ha-cambiado-el-sector-de-la-automocion/">Curiosidades</Contenido>
            </Sección>
            <Sección num_paginas="2">
                <Contenido información="https://www.cocheactual.com/venta-de-vehiculos-en-espana-no-recuperara-niveles-hasta-2030/">Curiosidades</Contenido>
            </Sección>
            <Sección num_paginas="1">
                <Contenido información="https://www.cocheactual.com/el-riesgo-de-la-conectividad-y-ciberseguridad-en-los-vehiculos-coches/">Curiosidades</Contenido>
            </Sección>
        </Secciones>
    </Revista>

</Biblioteca>