<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Biblioteca [
    <!ELEMENT Biblioteca (Periódico*)>

    <!ELEMENT Periódico (Secciones,Indice)>
    <!ATTLIST Periódico Id ID #REQUIRED>
    <!ATTLIST Periódico tipo_clase (nacional | internacional) #REQUIRED>
    <!ATTLIST Periódico fecha_publicación CDATA #REQUIRED>
    <!ELEMENT Secciones (Sección*)>

    <!ELEMENT Sección (Artículo*)>
    <!ATTLIST Sección tipo_sección (Económica | Opinión | Deportes | Nacional | Internacional) #REQUIRED>
    <!ATTLIST Sección num_paginas CDATA #REQUIRED>

    <!ELEMENT Artículo (#PCDATA)>
    <!ATTLIST Artículo Autor CDATA #REQUIRED>
    
    <!ELEMENT Indice (#PCDATA)> 
]>
<Biblioteca>
    <Periódico Id="P0519" tipo_clase="nacional" fecha_publicación="2023/02/23">
        <Secciones>
            <Sección tipo_sección="Actualidad">
                <Artículo Autor="Matias Prats">Se baja el IVA de los productos básicos</Artículo>
            </Sección>
            <Sección tipo_sección="Nacional">
                <Artículo Autor="Pedro Piqueras">Comienza la precampaña electoral</Artículo>
            </Sección>
            <Sección tipo_sección="Internacional">
                <Artículo Autor="Matias Prats">Se firma la paz en Ucrania</Artículo>
            </Sección>
            <Sección tipo_sección="Local">
                <Artículo Autor="José Ribagorda">Huelga de médicos en Madrid</Artículo>
            </Sección>
            <Sección tipo_sección="Cultura">
                <Artículo Autor="Isabel Jiménez">Comienza la fiesta del cine</Artículo>
            </Sección>   
            <Sección tipo_sección="Deportes">
                <Artículo Autor="Matias Prats Jr.">Real Madrid se prepara para las semifinales de la Liga de Campeones</Artículo>
            </Sección>
            <Sección tipo_sección="El tiempo">
                <Artículo Autor="Roberto Brasero">Nueva ola de calor llega a la península</Artículo>
            </Sección>     
        </Secciones>    
        <Indice>
            -Actualidad
            -Nacional
            -Internacional
            -Local
            -Cultura
            -Deportes
            -El tiempo
            -Anuncios
        </Indice>        
    </Periódico>
</Biblioteca>